name: Clean code

on: [push]

jobs:
  clean-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2, phpunit:v11.5
          coverage: xdebug, pcov
      
      - name: PHP Version Check
        run: php -v

      - name: Install Dependencies
        run: composer install

      - name: PHPUnit
        run: composer phpunit

      - name: Code Coverage
        use: docker://ghcr.io/ericsizemore/phpunit-coverage-check-action
        with:
          clover_file: 'clover.xml'
          threshold: 20

      - name: PHPStan
        run: composer phpstan
